version: 2
updates:
          # Maintain updates for github actions
        - package-ecosystem: "github-actions"
          directory: "/"
          schedule:
                  interval: "daily"

#           # Maintain updates for root npm
#         - package-ecosystem: "npm"
#           directory: "/"
#           schedule:
#                   interval: "daily"

#           # Maintain updates for backend npm
#         - package-ecosystem: "npm"
#           directory: "/backend"
#           schedule:
#                   interval: "daily"

#           # Maintain updates for frontend npm
#         - package-ecosystem: "npm"
#           directory: "/frontend"
#           schedule:
#                   interval: "daily"

