# -----------------------------------------------
# Base Image with Doppler
# -----------------------------------------------
FROM node:22 AS doppler

# TODO Maybe install manually
# pnpm install --prod --force @img/sharp-linux-arm64

# Install pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Install image manipulation tools
RUN apt-get update
RUN apt-get -y install ghostscript graphicsmagick libvips-tools

# Install dependencies
WORKDIR /app
COPY package.json .
RUN pnpm install 

# App
COPY . .

RUN pnpm run build 
RUN node build/test.js