# -----------------------------------------------
# Base Image with Doppler
# -----------------------------------------------
FROM node:22-alpine AS doppler

# TODO Maybe install manually
# pnpm install --prod --force @img/sharp-linux-arm64

# Install pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Install image manipulation tools
RUN apk update
RUN apk add ghostscript graphicsmagick 

# Install dependencies
WORKDIR /app
COPY package.json .
RUN pnpm install 

# Install libvips
RUN apk add vips-dev -U -X http://dl-3.alpinelinux.org/alpine/edge/testing/

# App
COPY . .

RUN pnpm run build 
RUN node build/test.js