events {
    worker_connections 1024;
}

http {
    # Redirect all HTTP to HTTPS
    server {
        listen 80;
        server_name www.hearing.3dp4me-software.org hearing.3dp4me-software.org
                    www.prosthetics.3dp4me-software.org prosthetics.3dp4me-software.org
                    www.pt.3dp4me-software.org pt.3dp4me-software.org;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;
        server_name www.hearing.3dp4me-software.org hearing.3dp4me-software.org;

        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        location / {
            client_max_body_size 100G;
            proxy_pass http://hearing_aid_web_app:5050/;
        }
    }

    server {
        listen 80;
        server_name www.prosthetics.3dp4me-software.org prosthetics.3dp4me-software.org;
        location / {
            client_max_body_size 100G;
            proxy_pass http://prosthetics_web_app:5051/;
        }
    }

    server {
        listen 80;
        server_name www.pt.3dp4me-software.org pt.3dp4me-software.org;
        location / {
            client_max_body_size 100G;
            proxy_pass http://pt_web_app:5052/;
        }
    }
}