name: backend

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.12.0

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./backend
        run: yarn

      - name: Check formatting
        working-directory: ./backend
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.12.0

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./backend
        run: yarn

      - name: Run linter
        working-directory: ./backend
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.12.0

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./backend
        run: yarn

      - name: Build application
        working-directory: ./backend
        run: yarn test
