name: client

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn

      - name: Check formatting
        working-directory: ./frontend
        run: yarn format:check

  lint:
    needs: check
    if: needs.check.outputs.run_jobs == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn

      - name: Install root dependencies
        working-directory: ./
        run: yarn

      - name: Run linter
        working-directory: ./frontend
        run: yarn lint

  build:
    needs: check
    if: needs.check.outputs.run_jobs == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn

      - name: Build application
        working-directory: ./frontend
        run: yarn build