# name: test

# on:
#   push:
#     branches:
#     - master
#   pull_request:
#     branches:
#     - master

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v2

#       - name: Set up Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Set up pnpm
#         uses: pnpm/action-setup@v4

#       - name: Install dependencies
#         run: pnpm install

#       - name: Test
#         run: pnpm run test